### ISSUE TITLE
conn.onTrack event fires after conn.close() is called

### ISSUE THREAD

**Issue by pimterry** [murat-dogan/node-datachannel#103]
I'm still looking into reproducing this more precisely, but right now I'm seeing an intermittent race condition with node-datachannel v0.3.1 that causes a segfault in about 1 in 5 of my test runs.

AFAICT, what's happening in the failing case is:

* Browser creates an offer for a connection, offering a data channel
* Node-datachannel creates an answer and accepts
* Browser creates an updated offer, additionally offering to receive video & audio
* Node-datachannel updates its answer to accept that too
* My test code waits for the connection to complete and for the track to appear (`conn.onTrack(() => ...)`) then immediately sends a message on the datachannel and closes the connection.
* After calling `conn.close()`, the `conn.onTrack(() => ...)` callback fires again, which triggers my code to run `track.onMessage(...)`, which segfaults [here](https://github.com/murat-dogan/node-datachannel/blob/896fe2b9927e3e4c58edeac72a9580eb910d69de/src/media-track-wrapper.cpp#L330) because mTrackPtr is zero, because it's been reset already by [`TrackWrapper::cleanCbsAndEraseInstance`](https://github.com/murat-dogan/node-datachannel/blob/896fe2b9927e3e4c58edeac72a9580eb910d69de/src/media-track-wrapper.cpp#L93).

In the more common successful case, the same steps happen, but the 2nd `onTrack` fires before `cleanCbsAndEraseInstance` is called, so it runs with no problems.

My code is doing mildly weird things here, granted, but imo this still shouldn't segfault. I think:

* `onTrack` shouldn't fire after `conn.close()` has returned.
* In the various track/channel JS wrappers, it would be useful to check if `mTrackPtr` is set before it's used, so that cases like this where methods are incorrectly called on tracks & channels after they're closed result in handleable & debuggable JS exceptions, not a hard segfault.

Happy to open a PR for the latter myself, if we agree that's a good idea? I'm not really sure where to start with the former (and I'm not totally sure if this is caused by the native side or by JS event scheduling or something).

In the short term I can work around this myself of course - I can track whether I've called `.close()` and then ignore future callbacks - but it'd be nicer if that was the default built-in behaviour so it was harder to accidentally crash like this.

**Comment by pimterry** [comment]
I have slightly more detail on what's going on here. On closer examination, the steps when this goes wrong are:

1. Track 1 onTrack fires
2. I call onMessage on track 1, all good
3. I call `conn.close()`
4. Track 1 is cleaned by `cleanCbsAndEraseInstance`
5. Track 2 onTrack fires
6. I call onMessage on track 2 -> segfault

I.e. track 2 never sees a call to `cleanCbsAndEraseInstance`, in both success & failure cases. Might be a memory leak there? Or it's cleaned up in some independent way at the same point, I'm not sure.

The only difference in the success case is that step 4 moves to the end, and then everything seems to work fine.

**Comment by paullouisageneau** [comment]
> After calling `conn.close()`, the `conn.onTrack(() => ...)` callback fires again

I think this is due to calling `cleanCbsAndEraseInstance` from the JavaScript state callback to allow running the JavaScript state callback after calling `close()`. It also allows the following sequence of events:
- `onTrack` is triggered, scheduling the JavaScript track callback on the event loop.
- The user calls `close()` from another JavaScript execution, as a result `onStateChange` is triggered, scheduling the JavaScript state callback on the event loop.
- The event loop runs the JavaScript track callack
- The event loop runs the JavaScript state callback for the closed state, which internally calls `cleanCbsAndEraseInstance`. Callbacks are reset, preventing new scheduling of callbacks, and the instance is unregistered, preventing execution of scheduled callbacks, but it's too late for the track callback.

**Comment by murat-dogan** [comment]
Hi,
We are calling `PeerConnection::cleanCbsAndEraseInstance` function after receiving `State::Closed` event. So for me we should not receive `onTrack` or any other callback again.  

Checking `mTrackPtr`, `mDataChannelPtr` before accessing the ptr could solve further problems. You can create a PR or I can create one next week.

I am not sure what you mean @paullouisageneau . The error appears on C++ bindings not JS side, so JS event loop could be delayed but in that case we should not hit an error on https://github.com/murat-dogan/node-datachannel/blob/896fe2b9927e3e4c58edeac72a9580eb910d69de/src/media-track-wrapper.cpp#L330

**Comment by pimterry** [comment]
> Checking mTrackPtr, mDataChannelPtr before accessing the ptr could solve further problems. You can create a PR or I can create one next week.

Done: #104

**Comment by paullouisageneau** [comment]
> We are calling PeerConnection::cleanCbsAndEraseInstance function after receiving State::Closed event. So for me we should not receive onTrack or any other callback again.

> I am not sure what you mean @paullouisageneau . The error appears on C++ bindings not JS side, so JS event loop could be delayed but in that case we should not hit an error on

The issue is that `cleanCbsAndEraseInstance()` is not called on `State::Closed` if the user set an `onStateClosed` JS callback. In that case, it is called when the `onStateClosed` JS callback actually runs on the event loop. 

Therefore, a JS callback can be called after `close()`: on the C++ side `onTrack` is triggered before `close()`, but due to the scheduling on the event loop the corresponding JavaScript callback is run between the call to `close()` and the `onStateClosed` JS callback.

Actually, calling `cleanCbsAndEraseInstance` from `onClose` introduces other issues, for instance here it results in an unsynchronized access to `instances` from another thread, as `cleanCbsAndEraseInstance` is run from the libdatachannel thread, not from the JavaScript event loop thread: https://github.com/murat-dogan/node-datachannel/blob/896fe2b9927e3e4c58edeac72a9580eb910d69de/src/data-channel-wrapper.cpp#L64

I'll try to refactor this to remove cleaning from `onClose`.


> > Checking mTrackPtr, mDataChannelPtr before accessing the ptr could solve further problems. You can create a PR or I can create one next week.
> 
> Done: #104

Great, thanks!

**Comment by murat-dogan** [comment]
> The issue is that cleanCbsAndEraseInstance() is not called on State::Closed if the user set an onStateClosed JS callback. In that case, it is called when the onStateClosed JS callback actually runs on the event loop.

Yes that's right.
What about this PR https://github.com/murat-dogan/node-datachannel/pull/105 ?

**Comment by paullouisageneau** [comment]
> What about this PR #105 ?

I think it doesn't fix the callback ordering issue as erasing the instance is actually what prevents already-scheduled callbacks from running. I'm attempting a refactoring to fix it.

**Comment by pimterry** [comment]
Amazing work, thanks guys!
