### ISSUE TITLE
Core dump with vitest and simple-peer

### ISSUE THREAD

**Issue by xurei** [murat-dogan/node-datachannel#222]
### Versions: 
- node-datachannel: `0.5.3`
- vitest: `1.3.1`
- simple-peer: `9.11.1`
- node: tested `18` and `20`, same behavior

All latest at the time of the creation of this issue.

### OS: 
Linux (Pop OS, most likely happening in Ubuntu too)

### Issue:
When I use Vitest to test the simplest code (taken from https://github.com/murat-dogan/node-datachannel/tree/master/examples/simple-peer-usage), vitest crashes with a core dump.  
I suspect it's because it runs in a Worker, maybe related to #129 ?

### Repository for reproduction: 
https://github.com/xurei/vitest-node-datachannel-crash

### Verbose log attached: 
[log.txt](https://github.com/murat-dogan/node-datachannel/files/14565108/log.txt)

I'm available if you need any more tests/informations on my side.

Note that I had a similar issue when I tried the same thing with `wrtc`, so it might be a problem on Vitest side.

**Comment by xurei** [comment]
Update: by using `vitest --pool=forks` instead of `vitest`, the issue goes away.

I don't know if/whether this should be fixed in this repository. Feel free to close this issue if you won't/can't fix this on your side. 🙂

**Comment by murat-dogan** [comment]
Hello,
thanks for reporting.
Could you please also try the latest release v0.5.4?

And also please check this issue and comment.
https://github.com/murat-dogan/node-datachannel/issues/172#issuecomment-1992553870

**Comment by xurei** [comment]
Thanks for the quick reply.

The core dump still happens with v0.5.4

I'm not sure how to add `node.cleanup()` in a vitest suite. 
I tried this 
```javascript
  afterEach(() => {
    node.cleanup()
  });
```
but I get `ReferenceError: node is not defined`.

Any idea ?

**Comment by murat-dogan** [comment]
You should import `import node from 'node-datachannel'`

And I think you should call cleanup just before exiting the test not after all

**Comment by murat-dogan** [comment]
It seems there is another issue, you can check here #223

**Comment by murat-dogan** [comment]
I have just published v0.5.5
Could you please try it?

**Comment by xurei** [comment]
Sorry for the delay.

I tried with `0.5.4` and `node.cleanup()` as you suggested. It works :tada: 

I also tried with `0.5.5`. It works even without `node.cleanup()` :tada: 

The live reload feature of vitest is apparently still broken (no big deal for me) :
```
FAIL node-datachannel.test.js [ node-datachannel.test.js ]
Error: Module did not self-register: '/home/olivier/vitest-node-datachannel-crash/node_modules/node-datachannel/build/Release/node_datachannel.node'.
 ❯ node_modules/node-datachannel/lib/index.js:5:25
```
No idea what it means 🤷  
See https://github.com/xurei/vitest-node-datachannel-crash/tree/v0.5.5-fix

**Comment by murat-dogan** [comment]
Hello,
https://github.com/murat-dogan/node-datachannel/releases/tag/v0.9.0
Could you also try with latest release?

**Comment by murat-dogan** [comment]
I am closing the issue. Please feel free to open if you need to.
